title: geemod
description: Scientific documentation for geeMod â€” a Google Earth Engine application
remote_theme: just-the-docs/just-the-docs

url: https://JoaoAlirio.github.io
baseurl: geemod

search_enabled: true
